const text = {
  title: "Bridgetafel",
  heading: "Speel Vijfkaart Hoog met een AI-partner",
  settings: "Instellingen",
  playMode: "Je speelt Noord en Zuid wanneer Noord/Zuid leider zijn; anders verdedig je als Zuid.",
  developerModeHelp: "Toont alle kaarten open, plus extra bied- en speeluitleg voor analyse en testen.",
  guidanceModeHelp: "Toont eenvoudige AI-suggesties met korte redenen. Dit is heuristische hulp, geen perfecte bridgeles.",
  playHistoryModeHelp: "Toont het live overzicht van gespeelde slagen tijdens het spel.",
  vulnerability: "Kwetsbaarheid",
  vulnerabilityNone: "Niemand",
  vulnerabilityNS: "Noord/Zuid",
  vulnerabilityEW: "Oost/West",
  vulnerabilityBoth: "Allen",
  bridgeScore: "Bridgescore",
  scoreFor: "Score voor",
  developerMode: "Developermodus",
  guidanceMode: "AI-suggesties",
  playHistoryMode: "Speelgeschiedenis",
  bidExplanations: "Bieduitleg",
  replayTitle: "Speel opnieuw",
  newHand: "Nieuwe hand",
  sameHand: "Zelfde hand",
  quickReview: "Test slagenoverzicht",
  seed: "Herhaalcode",
  loadSeed: "Laad code",
  copySeed: "Kopieer code",
  seedHelp: "Kopieer deze herhaalcode of plak een andere code om dezelfde hand of spelsituatie te laden.",
  seedCopied: "Herhaalcode gekopieerd.",
  seedLoaded: "Code geladen.",
  situationSeedLoaded: "Herhaalcode geladen.",
  situationSeedInvalid: "Deze herhaalcode kon niet worden geladen.",
  seedRequired: "Vul eerst een code in.",
  seedCopyFailed: "Kopieren lukte niet; selecteer de code handmatig.",
  openFeedback: "Feedback",
  openLessons: "Lessen",
  lessonsEyebrow: "Vijfkaart Hoog",
  lessonsTitle: "Lessen",
  lessonsIntro: "Kies een les. Les 1 is een echte instapmissie; de rest staat alvast in de leerroute klaar.",
  lessonStart: "Start oefening",
  lesson: "Les",
  lessonFeedback: "Lesfeedback",
  lessonBidFeedback: "Biedfeedback uit deze oefening",
  lessonPoints: "Lespunten",
  openGlossary: "Woordenlijst",
  openScoreTable: "Scoretabel",
  closeScoreTable: "Scoretabel sluiten",
  closeFeedback: "Sluiten",
  closeGlossary: "Sluiten",
  closeLessons: "Sluiten",
  glossaryTitle: "Verklarende woordenlijst",
  feedbackTitle: "Feedback",
  feedbackTypeLabel: "Type feedback",
  feedbackMessageLabel: "Bericht van tester",
  feedbackMessagePlaceholder: "Wat viel je op? Beschrijf waar je was en wat je verwachtte.",
  feedbackDetailLabel: "Extra toelichting",
  feedbackAnswerMissing: "_Niet ingevuld._",
  copyFeedback: "Kopieer feedback",
  mailFeedback: "Verstuur feedback",
  feedbackSubmitting: "Versturen...",
  feedbackHelp: "Klik op 'verstuur feedback'. De app stuurt je bericht en herhaalcode automatisch mee. Lukt dat niet, gebruik dan 'kopieer feedback'.",
  feedbackCopied: "Feedbackrapport gekopieerd.",
  feedbackCopyFailed: "Kopieren lukte niet; probeer de tekst handmatig te selecteren.",
  feedbackSubmitMissingEndpoint: "Feedback versturen is nog niet ingesteld; kopieer het rapport om het handmatig te sturen.",
  feedbackSubmitSending: "Feedback wordt verstuurd...",
  feedbackSubmitSent: "Feedback verstuurd. Dank je!",
  feedbackSubmitFailed: "Feedback versturen lukte niet; kopieer het rapport om het handmatig te sturen.",
  feedbackNoMessage: "_Geen bericht ingevuld._",
  feedbackSituationSeed: "Herhaalcode",
  feedbackTypes: {
    confusion: "Verwarring",
    bug: "Bug",
    rules: "Biedconventie/speelengine klopt niet",
    suggestion: "Suggestie"
  },
  feedbackPrompts: {
    confusion: {
      primaryLabel: "Wat was de verwarring?",
      primaryPlaceholder: "Beschrijf wat onduidelijk voelde of waar je vastliep."
    },
    bug: {
      primaryLabel: "Wat was de bug?",
      primaryPlaceholder: "Beschrijf wat er gebeurde en wat je verwachtte."
    },
    rules: {
      primaryLabel: "Wat klopte er niet?",
      primaryPlaceholder: "Noem het bod, de conventie, kaartkeuze of engine-uitkomst die niet klopt.",
      secondaryLabel: "Waarom klopt dit niet?",
      secondaryPlaceholder: "Leg kort uit welke bridgeafspraak, regel of verwachting hier volgens jou hoort."
    },
    suggestion: {
      primaryLabel: "Wat zou je verbeteren?",
      primaryPlaceholder: "Beschrijf de gewenste verbetering.",
      secondaryLabel: "Waarom is dit beter?",
      secondaryPlaceholder: "Leg kort uit wat dit duidelijker, leerzamer of prettiger maakt."
    }
  },
  recommendedBid: "AI-suggestie bod",
  recommendedCard: "AI-suggestie kaart",
  bidding: "Bieden",
  bidBox: "Biedbox",
  bidBoxYourTurn: "Biedbox · jij bent aan zet",
  history: "Speelgeschiedenis",
  review: "Handoverzicht",
  openingLead: "Eerste kaart",
  finalContract: "Contract",
  passedOut: "Rondpas",
  declarer: "Leider",
  dummy: "Dummy",
  result: "Resultaat",
  scoreExplanation: "Waarom deze score?",
  scoreContractGoal: "Nodig voor contract",
  scoreTricksMade: "Gehaalde slagen",
  scoreVulnerabilityEffect: "Kwetsbaarheid",
  scoreContractPoints: "Punten voor contract",
  scoreOvertricks: "Extra slagen",
  scoreUndertricks: "Te weinig slagen",
  scoreBonus: "Bonuspunten",
  scoreFinal: "Eindscore",
  scorePassOutGoal: "Er is geen contract, omdat iedereen heeft gepast.",
  scorePassOutTricks: "Er wordt niet gespeeld; beide paren krijgen 0.",
  auction: "Biedverloop",
  hands: "Handen",
  trickOverview: "Slagenoverzicht",
  reviewTrickKeyboardHelp: "Developermodus: gebruik \u2190 en \u2192 om door de slagen te lopen.",
  trickLegendLead: "Uit",
  trickLegendNSWin: "Noord/Zuid wint",
  trickLegendEWWin: "Oost/West wint",
  none: "Geen",
  board: "Bord",
  dealer: "Deler",
  tricks: "slagen",
  trick: "Slag",
  partner: "Partner",
  you: "Jij",
  by: "door",
  pass: "Pas",
  double: "X",
  redouble: "XX",
  stop: "Stop",
  alert: "Alert",
  advancedBidControlsOpen: "Toon Stop en Alert",
  advancedBidControlsClose: "Verberg Stop en Alert",
  stopAria: "Stopkaart voor je volgende bieding",
  alertAria: "Alertkaart bij je volgende bieding",
  bidExplanationPass: "Geen duidelijke systeemactie of te weinig waarden om te bieden.",
  bidExplanationDouble: "Doublet: voorlopig vooral een informatiedoublet of strafdoublet in duidelijke situaties.",
  bidExplanationRedouble: "Redoublet: toont extra waarden na een doublet van de tegenpartij; mogelijk is er later een strafkans.",
  bidExplanationOpening: "Opening: {detail}.",
  bidExplanationResponse: "Antwoord op partner: {detail}.",
  bidExplanationCompetitive: "Competitieve actie: {detail}.",
  bidExplanationContinuation: "Vervolg: {detail}.",
  bidExplanationArtificial: "Kunstmatige afspraak: {detail}.",
  playExplanations: "Speeluitleg",
  playPlan: "Speelplan",
  playPlanGoal: "Doel",
  playPlanPriorities: "Prioriteiten",
  playPlanWarnings: "Let op",
  sureWinners: "Vaste slagen",
  loserCount: "Verliezers",
  hint: "Hint",
  auctionInProgress: "Bieden bezig",
  dealToStart: "Deel een hand om te starten",
  chooseAndDeal: "Deel een nieuwe hand om te starten.",
  historyEmpty: "Slagen verschijnen hier tijdens het spel.",
  opensAuction: "{seat} opent het bieden.",
  yourCall: "Jij bent aan de beurt om te bieden.",
  fourPasses: "Vier passen. Score 0 op dit bord.",
  lead: "{leader} komt uit. Leider: {declarer}. Dummy: {dummy}.",
  dummyNoticeDeclaring: "{dummy} is dummy: {declarer} is leider, dus jij speelt nu beide Noord/Zuid-handen.",
  dummyNoticeDefending: "{dummy} is dummy: {declarer} is leider, dus {dummy} ligt open. Jij verdedigt als Zuid.",
  yourOpeningLead: "Jij komt uit. Kies een kaart.",
  yourPlay: "Jij bent aan de beurt. Bekennen als dat kan.",
  illegalCardFollowSuit: "Bekennen: speel eerst {suit}.",
  illegalCardWrongTurn: "{seat} is niet aan de beurt. {turn} moet spelen.",
  illegalCardWaitTrick: "Wacht op de volgende slag.",
  illegalCardGeneric: "Deze kaart kan nu niet.",
  played: "{seat} speelde {card}.",
  winsTrick: "{seat} wint slag {number}.",
  contractResult: "{contract} door {declarer}: {result}.",
  passOutResult: "Rondpas: score 0",
  situationTurn: "Situatie geladen. {seat} is aan zet.",
  made: "gemaakt +{over}",
  down: "{under} down",
  declarers: "Leidersteam",
  defenders: "tegenspelers",
  northSouth: "Noord/Zuid",
  eastWest: "Oost/West",
  seats: { North: "Noord", East: "Oost", South: "Zuid", West: "West" },
  suits: { C: "klaveren", D: "ruiten", H: "harten", S: "schoppen", NT: "sans-atout" }
};
