const text = {
  title: "Bridgetafel",
  heading: "Speel Vijfkaart Hoog met een AI-partner",
  settings: "Instellingen",
  playMode: "Je speelt Noord en Zuid wanneer Noord/Zuid leider zijn; anders verdedig je als Zuid.",
  developerModeHelp: "Toont alle kaarten open, plus extra bied- en speeluitleg voor analyse en testen.",
  guidanceModeHelp: "Toont eenvoudige AI-suggesties met korte redenen. Dit is heuristische hulp, geen perfecte bridgeles.",
  playHistoryModeHelp: "Toont het live overzicht van gespeelde slagen tijdens het spel.",
  vulnerability: "Kwetsbaarheid",
  vulnerabilityNone: "Niemand",
  vulnerabilityNS: "Noord/Zuid",
  vulnerabilityEW: "Oost/West",
  vulnerabilityBoth: "Allen",
  bridgeScore: "Bridgescore",
  scoreFor: "Score voor",
  developerMode: "Developermodus",
  guidanceMode: "AI-suggesties",
  playHistoryMode: "Speelgeschiedenis",
  bidExplanations: "Bieduitleg",
  newHand: "Nieuwe hand",
  sameHand: "Zelfde hand",
  quickReview: "Test slagenoverzicht",
  seed: "Handseed",
  loadSeed: "Laad seed",
  copySeed: "Kopieer seed",
  seedHelp: "Kopieer deze seed of plak een andere seed om dezelfde kaartverdeling op dit bord te laden.",
  seedCopied: "Seed gekopieerd.",
  seedLoaded: "Seed geladen.",
  seedRequired: "Vul eerst een seed in.",
  seedCopyFailed: "Kopieren lukte niet; selecteer de seed handmatig.",
  openFeedback: "Feedback",
  closeFeedback: "Sluiten",
  feedbackTitle: "Feedback",
  feedbackTypeLabel: "Type feedback",
  feedbackMessageLabel: "Bericht van tester",
  feedbackMessagePlaceholder: "Wat viel je op? Beschrijf waar je was en wat je verwachtte.",
  feedbackContextLabel: "Handgegevens toevoegen",
  copyFeedback: "Kopieer feedback",
  mailFeedback: "Mail feedback",
  feedbackHelp: "Kopieer een Markdown-rapport of open een e-mail met seed, biedverloop, slagen, score en instellingen. Er wordt niets automatisch verstuurd.",
  feedbackCopied: "Feedbackrapport gekopieerd.",
  feedbackCopyFailed: "Kopieren lukte niet; probeer de tekst handmatig te selecteren.",
  feedbackMailOpened: "E-mail geopend.",
  feedbackMailFailed: "E-mail openen lukte niet; kopieer het rapport handmatig.",
  feedbackMailContextTooLong: "Het volledige rapport was te lang voor een mailto-link. Gebruik 'Kopieer feedback' voor de volledige context.",
  feedbackNoMessage: "_Geen bericht ingevuld._",
  feedbackPhase: "Fase",
  feedbackCurrentTurn: "Aan zet",
  feedbackSettings: "Instellingen",
  feedbackOriginalHands: "Handen bij start",
  feedbackCurrentTrick: "Lopende slag",
  feedbackWinner: "Winnaar",
  feedbackTypes: {
    confusion: "Verwarring",
    bug: "Bug",
    rules: "Regel of score klopt niet",
    suggestion: "Suggestie"
  },
  recommendedBid: "AI-suggestie bod",
  recommendedCard: "AI-suggestie kaart",
  bidding: "Bieden",
  history: "Speelgeschiedenis",
  review: "Handoverzicht",
  openingLead: "Uitkomst",
  finalContract: "Contract",
  passedOut: "Rondpas",
  declarer: "Leider",
  dummy: "Dummy",
  result: "Resultaat",
  scoreExplanation: "Score-uitleg",
  scoreContractGoal: "Contractdoel",
  scoreTricksMade: "Gehaald",
  scoreVulnerabilityEffect: "Kwetsbaarheid",
  scoreContractPoints: "Contractpunten",
  scoreOvertricks: "Overslagen",
  scoreUndertricks: "Onderslagen",
  scoreBonus: "Bonus",
  scoreFinal: "Eindscore",
  scorePassOutGoal: "Er is geen contract, omdat iedereen heeft gepast.",
  scorePassOutTricks: "Er wordt niet gespeeld; beide paren krijgen 0.",
  auction: "Biedverloop",
  hands: "Handen",
  trickOverview: "Slagenoverzicht",
  trickLegendLead: "Uit",
  trickLegendNSWin: "Noord/Zuid wint",
  trickLegendEWWin: "Oost/West wint",
  none: "Geen",
  board: "Bord",
  dealer: "Deler",
  tricks: "slagen",
  trick: "Slag",
  partner: "Partner",
  you: "Jij",
  by: "door",
  pass: "Pas",
  double: "Doublet",
  redouble: "Redoublet",
  stop: "Stop",
  alert: "Alert",
  stopAria: "Stopkaart voor je volgende bieding",
  alertAria: "Alertkaart bij je volgende bieding",
  bidExplanationPass: "Geen duidelijke systeemactie of te weinig waarden om te bieden.",
  bidExplanationDouble: "Doublet: voorlopig vooral een informatiedoublet of strafdoublet in duidelijke situaties.",
  bidExplanationRedouble: "Redoublet: toont extra vertrouwen nadat de tegenpartij heeft gedoubleerd.",
  bidExplanationOpening: "Opening: {detail}.",
  bidExplanationResponse: "Antwoord op partner: {detail}.",
  bidExplanationCompetitive: "Competitieve actie: {detail}.",
  bidExplanationContinuation: "Vervolg: {detail}.",
  bidExplanationArtificial: "Kunstmatige afspraak: {detail}.",
  playExplanations: "Speeluitleg",
  playPlan: "Speelplan",
  playPlanGoal: "Doel",
  playPlanPriorities: "Prioriteiten",
  playPlanWarnings: "Let op",
  sureWinners: "Vaste slagen",
  loserCount: "Verliezers",
  hint: "Hint",
  auctionInProgress: "Bieden bezig",
  dealToStart: "Deel een hand om te starten",
  chooseAndDeal: "Deel een nieuwe hand om te starten.",
  historyEmpty: "Slagen verschijnen hier tijdens het spel.",
  opensAuction: "{seat} opent het bieden.",
  yourCall: "Jij bent aan de beurt om te bieden.",
  fourPasses: "Vier passen. Score 0 op dit bord.",
  lead: "{leader} komt uit. Leider: {declarer}. Dummy: {dummy}.",
  dummyNoticeDeclaring: "{dummy} is dummy: {declarer} is leider, dus jij speelt nu beide Noord/Zuid-handen.",
  dummyNoticeDefending: "{dummy} is dummy: {declarer} is leider, dus {dummy} ligt open. Jij verdedigt als Zuid.",
  yourPlay: "Jij bent aan de beurt. Bekennen als dat kan.",
  played: "{seat} speelde {card}.",
  winsTrick: "{seat} wint slag {number}.",
  contractResult: "{contract} door {declarer}: {result}.",
  passOutResult: "Rondpas: score 0",
  made: "gemaakt +{over}",
  down: "{under} down",
  declarers: "Leidersteam",
  defenders: "tegenspelers",
  northSouth: "Noord/Zuid",
  eastWest: "Oost/West",
  seats: { North: "Noord", East: "Oost", South: "Zuid", West: "West" },
  suits: { C: "klaveren", D: "ruiten", H: "harten", S: "schoppen", NT: "sans-atout" }
};
