const { assert, rules, test } = require("./harness.js");

test("bridge-rules public API stays stable", () => {
  const expectedApi = [
    "Bid",
    "Double",
    "Pass",
    "Redouble",
    "auctionComplete",
    "beats",
    "bidStrains",
    "biddingSystems",
    "calculateBridgeScore",
    "calculatePassOutScore",
    "callTypes",
    "canDoubleFromAuction",
    "canRedoubleFromAuction",
    "chooseBid",
    "chooseCardPlay",
    "chooseFiveCardHighBid",
    "chooseFiveCardHighBidResult",
    "chooseFiveCardHighBidTarget",
    "chooseFiveCardHighOpenerRebid",
    "chooseFiveCardHighOpening",
    "chooseFiveCardHighResponderRebid",
    "chooseFiveCardHighResponse",
    "compareCards",
    "contractTrickPoints",
    "countSuits",
    "createDeck",
    "createPlayPlan",
    "currentWinningPlay",
    "dealerIndexForDeal",
    "dealHands",
    "downScore",
    "finalContract",
    "findDeclarer",
    "fitPoints",
    "handShape",
    "handSuitOrder",
    "hcp",
    "highestBid",
    "highestBidCall",
    "isBidHigher",
    "isContractBid",
    "isContractCall",
    "isDouble",
    "isPass",
    "isRedouble",
    "isTeamVulnerable",
    "legalCards",
    "normalizeBid",
    "overtrickPoints",
    "partnerOf",
    "randomFromSeed",
    "rankOrder",
    "sameCall",
    "seats",
    "suits",
    "teamOf",
    "vulnerabilityForDeal"
  ];

  assert.deepEqual(Object.keys(rules).sort(), expectedApi.sort());
});
